{"name": "test_mul_004", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_file_003.Test_Credence_003 object at 0x000001A0E6B56BD0>\n\n>   ???\nE   assert False\n\nD:\\Credence Class Notes\\CredenceBatches\\CredenceBatch#14 & 15\\Pytest_July\\test_file_003.py:11: AssertionError"}, "attachments": [{"name": "stdout", "source": "271021eb-a323-4967-8516-62dad552f2bd-attachment.txt", "type": "text/plain"}], "start": 1690695016105, "stop": 1690695016105, "uuid": "33ce6de6-01af-4777-80af-fd3a8d8ba46b", "historyId": "1da0023011657c42a38b1de108e70725", "testCaseId": "1da0023011657c42a38b1de108e70725", "fullName": "test_file_003.Test_Credence_003#test_mul_004", "labels": [{"name": "suite", "value": "test_file_003"}, {"name": "subSuite", "value": "Test_Credence_003"}, {"name": "host", "value": "DESKTOP-S60SV8I"}, {"name": "thread", "value": "7456-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file_003"}]}